---

# version: '3.8'

env_file: .env

services:
  server:
    build: 
      context: .   
      dockerfile: Dockerfile
    container_name: ricette-server
    restart: always
    expose:
      - "3000"
    networks:
      - ricette-network
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: mysql:8
    container_name: mysql-ricette
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - ricette-network
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - ricette-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server

volumes:
  mysql-data:



# avvio container on .env: docker compose --env-file .env up -d --build

